name: Build JAR

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger le projet
        uses: actions/checkout@v4

      - name: Installer Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Extraire le projet
        run: unzip -o "AntiCheatTotem (1).zip" -d project

      - name: Compiler avec Maven
        run: |
          POM=$(find project -name pom.xml -print -quit)
          echo "POM trouvé : $POM"
          mvn -f "$POM" clean package

      - name: Récupérer le JAR
        uses: actions/upload-artifact@v4
        with:
          name: AntiCheatTotem-JAR
          path: project/**/target/*.jar
